[pytest]
markers =
    api: marks tests as API tests
    ui: marks tests as UI tests
addopts = 
    -v 
    --alluredir=allure-results
    --clean-alluredir
testpaths = test
python_files = test_*.py *_test.py 
python_classes = Test*
python_functions = test_*